### ISSUE TITLE
Update supertokens-android with latest logic for session management

### ISSUE THREAD

**Issue by nkshah2** [supertokens/supertokens-android#10]
## TODOs

- [x] Update the config parameters that the SDK accepts during SuperTokens.init
- [x] ~~Add Pre API hooks~~ Add a way to add custom headers for requests made by the SDK
- [x] Add the event handler (OnHandleEvent)
- [x] Add logic to set/remove the front token
- [x] Make sure the request logic (interception, reading/setting headers etc) is up to date
- [x] Change the package name to use `com.supertokens` instead of `io.supertokens`
- [x] Missing functions to expose:
   - [x] `getUserId`
   - [x] `getAccessTokenPayloadSecurely`
   - [x] `attemptRefreshingSession`
   - [x] `signOut`
- [x] Add logic for `doNotDoInterception`
- [x] Remove adding of `PACKAGE_PLATFORM` and `VERSION_NAME`
- [x] ~~Remove `preConnectCallback`~~ [ We need this for HTTPUrlConnection so users can add custom properties to the connection object]
- [x] ~~Need to add credentials include in the request header?~~ [Not required]
- [x] Add header for `rid` and set it to `anti-csrf` if the user has not done that already
- [x] Add front-token:
   - [x] When you are setting anti-csrf token in doRequest
   - [x] Post refresh API call
- [x] Remove front-token:
   - [x] When we remove anti-csrf
   - [x] Finally block of refresh function if the idRefreshToken doesn't exist  
- [x] Remove need for `handleUnauthorised` function
- [x] Remove this `if` statement: https://github.com/supertokens/supertokens-android/blob/update-init-logic/app/src/main/java/io/supertokens/session/SuperTokensHttpURLConnection.java#L118

```
if ( preRequestIdRefreshToken == null ) {
            String idRefreshToken = IdRefreshToken.getToken(applicationContext);
            return idRefreshToken != null;
        }
```

- [x] When refresh is called, add `rid: session` and `fdi-version` headers
- [x] In the finally block of function that calls refresh API, we should check if idRefreshToken exists, and if not, remove anti-csrf and frontend token
- [x] Verify if locking is needed in token classes
- [ ] Override / recipeImplementation abstraction
- [ ] User context
- [x] Upgrade android properties
    - [x] Test with latest target sdk and compile sdk versions and update
    - [x] Update to latest okhttp and retrofit versions
    - [x] Upgrade to latest gradle?
    - [x] Check if min sdk version needs to change
    - [x] Double check progaurd rules

**Comment by nkshah2** [comment]
> Need to add credentials include in the request header?

Not required
